apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: guide
  name: guide-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi