apiVersion: v1
kind: Service
metadata:
  namespace: guide
  name: nestjs-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: nestjs
---
apiVersion: v1
kind: Service
metadata:
  name: external-guide
  namespace: guide
spec:
  type: ExternalName
  externalName: guide.local
  ports:
    - port: 3000
  selector:
    app: nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guide
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nestjs
          imagePullPolicy: Always
          image: ${DOCKER_REPOSITORY_KUBERNETES_URL}/hackathonguide:v1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: guide-secret
          env:
            - name: TYPEORM_CONNECTION
              value: "${TYPEORM_CONNECTION}"
            - name: TYPEORM_HOST
              value: "${TYPEORM_HOST}"
            - name: TYPEORM_USERNAME
              value: "${TYPEORM_USERNAME}"
            - name: TYPEORM_PORT
              value: "${TYPEORM_PORT}"
            - name: TYPEORM_SYNCHRONIZE
              value: "${TYPEORM_SYNCHRONIZE}"
            - name: TYPEORM_LOGGING
              value: "${TYPEORM_LOGGING}"
            - name: TYPEORM_ENTITIES
              value: "${TYPEORM_ENTITIES}"
            - name: TYPEORM_MIGRATIONS
              value: "${TYPEORM_MIGRATIONS}"
            - name: TYPEORM_ENTITIES_DIR
              value: "${TYPEORM_ENTITIES_DIR}"
            - name: TYPEORM_MIGRATIONS_DIR
              value: "${TYPEORM_MIGRATIONS_DIR}"
            - name: TYPEORM_DATABASE
              value: "${TYPEORM_DATABASE}"